title: Fabien Messinger
ogo: /img/Fabien_id.jpg
theme: jekyll-theme-minimal
show_downloads: false

email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Transformer la donn√©e en insight
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://example.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  episodes:
    output: true
  seasons:
    output: true
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "seasons"
    values:
      layout: "season"
